spring:
  application:
    name: banco

  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost:5432/banco}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
      max-idle-time: 30m

  sql:
    init:
      mode: always
      platform: postgres
      continue-on-error: false

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    io.r2dbc.postgresql: INFO
    org.springframework.r2dbc: INFO