spring:
  application:
    name: banco

  r2dbc:
    url: r2dbc:postgresql://dpg-4d5l4k9k6d8rns7i3p0da2-a:5432/banco_db_39pd
    username: banco_db_30pd_user
    password: AaYGMlog8BoCwNF5qyfDRIAnKLp5jmRY

  sql:
    init:
      mode: always
      platform: postgres

server:
  error:
    include-message: always
    include-binding-errors: always
