spring:
  application:
    name: banco

  r2dbc:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    properties:
        ssl: true

  sql:
    init:
      mode: always
      platform: postgres

server:
  error:
    include-message: always
    include-binding-errors: always
