spring:
  application:
    name: banco

  r2dbc:
    url: ${DB_URL}?ssl=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}


  sql:
    init:
      mode: always
      platform: postgres

server:
  error:
    include-message: always
    include-binding-errors: always

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration